"""
Pygame client for Fuzhou Mahjong.

Architecture
------------
The client holds a `GameState` that is either (a) owned locally when playing
against AI, or (b) a mirror kept in sync with a remote server when playing
online.  Rendering is a pure function of the current state; input events are
translated into `Action`s that are either applied locally or forwarded to the
server.

Authentic table styling
-----------------------
  * Deep green felt background with a subtle vignette.
  * Ivory tiles generated by ``render_tiles.py``.
  * Four seats laid out around the table (South is the local player),
    with other seats rendering as face-down backs unless the game is in a
    "show hands" mode.
  * Discards pile up in the centre rectangle.
  * Score bar along the top shows each player's running score and who the
    dealer is.
"""
from __future__ import annotations

import argparse
import math
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pygame

from ..game import (
    Action, ActionType, GameState, MeldType, Phase, Tile, check_win,
    find_calls, find_concealed_kongs,
)
from ..game.ai import AIPlayer
from . import render_tiles


# ------------------------------------------------------------- constants

WINDOW_W, WINDOW_H = 1280, 800
FELT_GREEN = (20, 90, 55)
FELT_DARK = (14, 60, 38)
IVORY_TEXT = (248, 238, 212)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GOLD = (218, 170, 50)
RED = (200, 40, 40)
BTN = (80, 60, 40)
BTN_HOVER = (120, 90, 60)

FPS = 60

# ── Man-tile legend ────────────────────────────────────────────────────────
# Each row: (CJK character shown on tile, English reading)
MAN_LEGEND = [
    ("一", "1  —  One"),
    ("二", "2  —  Two"),
    ("三", "3  —  Three"),
    ("四", "4  —  Four"),
    ("五", "5  —  Five"),
    ("六", "6  —  Six"),
    ("七", "7  —  Seven"),
    ("八", "8  —  Eight"),
    ("九", "9  —  Nine"),
    ("萬", "Wan  (suit name)"),
]


def _find_pygame_cjk_font(size: int) -> Optional[pygame.font.Font]:
    """Return a pygame Font that can render CJK characters, or None."""
    candidates = [
        "C:/Windows/Fonts/msyh.ttc",      # Microsoft YaHei (Win)
        "C:/Windows/Fonts/simsun.ttc",     # SimSun (Win)
        "C:/Windows/Fonts/simhei.ttf",     # SimHei (Win)
        "/System/Library/Fonts/PingFang.ttc",
        "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
    ]
    for p in candidates:
        if os.path.exists(p):
            try:
                return pygame.font.Font(p, size)
            except Exception:
                continue
    return None


def _get_asset_dir() -> Path:
    """Return the tiles asset directory, works both normally and inside a
    PyInstaller bundle (where sys._MEIPASS holds the extracted package root)."""
    if getattr(sys, "frozen", False):
        # Running as a PyInstaller .exe — assets are extracted to _MEIPASS
        base = Path(sys._MEIPASS)  # type: ignore[attr-defined]
    else:
        base = Path(__file__).resolve().parent.parent
    return base / "assets" / "tiles"


ASSET_DIR = _get_asset_dir()


# ------------------------------------------------------------- asset loader


class TileCache:
    """Loads + caches the per-tile PNGs.  Auto-generates them if missing.

    Tiles are kept at their source resolution internally and rescaled on
    demand to whatever the current window size calls for.  The client calls
    :meth:`set_tile_width` each frame; if the requested width changes we
    rebuild the scaled surface cache so hand / small / back tiles stay in
    lockstep with the window."""

    # Ratio of "small" (discard / meld) tiles to full hand tiles.
    SMALL_RATIO = 0.62

    def __init__(self, initial_width: int = 72):
        if not (ASSET_DIR / "back.png").exists():
            render_tiles.generate_all(ASSET_DIR)
        self._base: Dict[str, pygame.Surface] = {}
        for f in ASSET_DIR.glob("*.png"):
            self._base[f.stem] = pygame.image.load(str(f)).convert_alpha()
        base_back = self._base["back"]
        self._base_w = base_back.get_width()
        self._base_h = base_back.get_height()
        self._scaled: Dict[Tuple[str, int], pygame.Surface] = {}
        self._tile_w = 0
        self._tile_h = 0
        self._small_w = 0
        self._small_h = 0
        self._opp_w = 0
        self._opp_h = 0
        self.set_sizes(initial_width, max(22, int(initial_width * 0.55)))

    # ------------------------------------------------ sizing
    def set_sizes(self, main_w: int, opp_w: int) -> bool:
        """Resize rendered tile widths.

        ``main_w`` controls the local player's concealed hand (and anything
        derived from it, via :attr:`small_w`).  ``opp_w`` controls the
        face-down tiles shown for the other three seats; they get a separate
        scale so 16 rotated backs can fit down the side of the window without
        overflowing.  Returns True if anything changed."""
        main_w = max(24, min(int(main_w), self._base_w))
        opp_w = max(18, min(int(opp_w), main_w))
        if main_w == self._tile_w and opp_w == self._opp_w:
            return False
        self._tile_w = main_w
        self._tile_h = max(24, int(main_w * self._base_h / self._base_w))
        self._small_w = max(18, int(main_w * self.SMALL_RATIO))
        self._small_h = max(18, int(self._small_w * self._base_h / self._base_w))
        self._opp_w = opp_w
        self._opp_h = max(18, int(opp_w * self._base_h / self._base_w))
        # Invalidate the scaled cache — otherwise it would grow unbounded.
        self._scaled.clear()
        return True

    # Backwards-compat shim: earlier code called set_tile_width(...) only.
    def set_tile_width(self, w: int) -> bool:
        return self.set_sizes(w, max(22, int(w * 0.55)))

    # ------------------------------------------------ rendering
    def _scaled_img(self, key: str, w: int, h: int) -> pygame.Surface:
        cache_key = (key, w)
        surf = self._scaled.get(cache_key)
        if surf is None:
            surf = pygame.transform.smoothscale(self._base[key], (w, h))
            self._scaled[cache_key] = surf
        return surf

    def _key(self, tile: Tile) -> str:
        return tile.to_id().replace(":", "_")

    def face(self, tile: Tile) -> pygame.Surface:
        return self._scaled_img(self._key(tile), self._tile_w, self._tile_h)

    def small(self, tile: Tile) -> pygame.Surface:
        return self._scaled_img(self._key(tile), self._small_w, self._small_h)

    def back(self) -> pygame.Surface:
        return self._scaled_img("back", self._tile_w, self._tile_h)

    def small_back(self) -> pygame.Surface:
        return self._scaled_img("back", self._small_w, self._small_h)

    def opp_back(self) -> pygame.Surface:
        """Back tile sized for the other three seats."""
        return self._scaled_img("back", self._opp_w, self._opp_h)

    @property
    def tile_w(self) -> int:
        return self._tile_w

    @property
    def tile_h(self) -> int:
        return self._tile_h

    @property
    def small_w(self) -> int:
        return self._small_w

    @property
    def small_h(self) -> int:
        return self._small_h

    @property
    def opp_w(self) -> int:
        return self._opp_w

    @property
    def opp_h(self) -> int:
        return self._opp_h


# ------------------------------------------------------------- layout helpers


def _rotate(surf: pygame.Surface, deg: int) -> pygame.Surface:
    return pygame.transform.rotate(surf, deg) if deg else surf


# ------------------------------------------------------------- button


class Button:
    def __init__(self, rect: pygame.Rect, label: str, value: str = ""):
        self.rect = rect
        self.label = label
        self.value = value or label
        self.hovered = False
        self.enabled = True

    def draw(self, surf: pygame.Surface, font: pygame.font.Font) -> None:
        color = BTN_HOVER if self.hovered and self.enabled else BTN
        if not self.enabled:
            color = (60, 50, 40)
        pygame.draw.rect(surf, color, self.rect, border_radius=6)
        pygame.draw.rect(surf, IVORY_TEXT, self.rect, 2, border_radius=6)
        txt = font.render(self.label, True, IVORY_TEXT if self.enabled else (140, 130, 110))
        surf.blit(txt, txt.get_rect(center=self.rect.center))

    def handle(self, event) -> bool:
        if not self.enabled:
            return False
        if event.type == pygame.MOUSEMOTION:
            self.hovered = self.rect.collidepoint(event.pos)
        elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            if self.rect.collidepoint(event.pos):
                return True
        return False


# ------------------------------------------------------------- main client


class Client:
    """Runs the Pygame loop against either a local AI game or a remote session."""

    def __init__(
        self,
        my_seat: int = 0,
        local_ais: Optional[List[int]] = None,
        gs: Optional[GameState] = None,
        network: Optional["NetworkClient"] = None,
        seed: Optional[int] = None,
    ):
        pygame.init()
        pygame.display.set_caption("Fuzhou Mahjong")
        self.fullscreen = False
        self.screen = pygame.display.set_mode((WINDOW_W, WINDOW_H), pygame.RESIZABLE)
        self.clock = pygame.time.Clock()
        self.tiles = TileCache(initial_width=72)
        self._last_viewport: Tuple[int, int] = (0, 0)
        self.my_seat = my_seat
        self.network = network
        self.font = pygame.font.SysFont("arial", 18)
        self.font_big = pygame.font.SysFont("arial", 28, bold=True)
        self.font_small = pygame.font.SysFont("arial", 14)
        # CJK font for the Man-tile legend (None if unavailable on this system)
        self.font_cjk = _find_pygame_cjk_font(16)
        self.show_legend = True   # toggle with L key

        self.gs = gs or GameState.new_game(
            ["You", "Player 2", "Player 3", "Player 4"], seed=seed,
        )
        self.local_ais: Dict[int, AIPlayer] = {}
        for seat in (local_ais or []):
            self.local_ais[seat] = AIPlayer(seat, seed=seat)

        self.selected_tile: Optional[Tile] = None
        self.status_msg = ""
        self.buttons: List[Button] = []

    # ------------------------------------------------ screen size helpers

    @property
    def w(self) -> int:
        return self.screen.get_width()

    @property
    def h(self) -> int:
        return self.screen.get_height()

    def _toggle_fullscreen(self) -> None:
        self.fullscreen = not self.fullscreen
        if self.fullscreen:
            self.screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
        else:
            self.screen = pygame.display.set_mode((WINDOW_W, WINDOW_H), pygame.RESIZABLE)

    # ------------------------------------------------ responsive layout

    # Target hand capacity: up to 17 tiles for a dealer + lifted last draw.
    _HAND_SLOTS = 17
    _HAND_GAP = 4

    def _update_layout(self) -> None:
        """Pick tile sizes so the hand + opponent hands all fit on-screen.

        Called every frame (cheap — :class:`TileCache` only rebuilds scaled
        surfaces when the chosen size actually changes)."""
        viewport = (self.w, self.h)
        base_w = self.tiles._base_w
        base_h = self.tiles._base_h

        # --- Main tile width: fits the local player's concealed hand row.
        side_margin = 40
        available_w = max(200, self.w - side_margin * 2)
        slots = self._HAND_SLOTS
        per_tile = (available_w - (slots - 1) * self._HAND_GAP) // slots
        main_w = max(32, min(per_tile, base_w))

        # --- Opponent back width: chosen so 16 tiles fit down the side seats
        # (rotated 90° — rotated height == back width) and across the top.
        opp_slots = 17
        avail_h = max(300, self.h - 220)
        avail_w_top = max(400, self.w - 320)   # leave room for side columns
        w_by_side = (avail_h - (opp_slots - 1) * 3) // opp_slots
        w_by_top = (avail_w_top - (opp_slots - 1) * 3) // opp_slots
        opp_w = max(22, min(w_by_side, w_by_top, main_w))

        self.tiles.set_sizes(main_w=main_w, opp_w=opp_w)
        self._last_viewport = viewport

    # ------------------------------------------------ running

    def run(self) -> None:
        try:
            while True:
                self._tick()
        except SystemExit:
            pygame.quit()

    def _tick(self) -> None:
        self._run_ais()
        self._handle_events()
        self._draw()
        pygame.display.flip()
        self.clock.tick(FPS)

    # ------------------------------------------------ AI driver

    def _run_ais(self) -> None:
        if self.network is not None:
            return   # the server drives turns for remote bots
        gs = self.gs
        if gs.phase == Phase.WAITING_DRAW and gs.current_seat in self.local_ais:
            gs.apply(Action(ActionType.DRAW, seat=gs.current_seat))
        elif gs.phase == Phase.WAITING_DISCARD and gs.current_seat in self.local_ais:
            ai = self.local_ais[gs.current_seat]
            pygame.time.delay(400)   # slight pacing so it's readable
            gs.apply(ai.act_on_turn(gs))
        elif gs.phase == Phase.WAITING_CALLS:
            for seat, calls in list(gs.pending_calls.items()):
                if seat in self.local_ais:
                    gs.apply(self.local_ais[seat].act_on_call(gs, calls))
                    if gs.phase != Phase.WAITING_CALLS:
                        break

    # ------------------------------------------------ input

    def _handle_events(self) -> None:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit(0)
            if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                if self.fullscreen:
                    self._toggle_fullscreen()
                else:
                    pygame.quit(); sys.exit(0)
            if event.type == pygame.KEYDOWN and event.key == pygame.K_F11:
                self._toggle_fullscreen()
            if event.type == pygame.KEYDOWN and event.key == pygame.K_l:
                self.show_legend = not self.show_legend
            if event.type == pygame.VIDEORESIZE and not self.fullscreen:
                self.screen = pygame.display.set_mode(
                    (max(640, event.w), max(480, event.h)), pygame.RESIZABLE,
                )

            for b in self.buttons:
                if b.handle(event):
                    self._on_button(b)

            if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                self._on_click(event.pos)

    def _on_click(self, pos: Tuple[int, int]) -> None:
        # Click on own concealed tiles to select / discard.
        hand_rects = self._layout_my_hand()
        for tile, rect in hand_rects:
            if rect.collidepoint(pos):
                if self.selected_tile == tile:
                    self._try_discard(tile)
                else:
                    self.selected_tile = tile
                return

    def _on_button(self, b: Button) -> None:
        gs = self.gs
        seat = self.my_seat
        if b.value == "draw":
            if gs.phase == Phase.WAITING_DRAW and gs.current_seat == seat:
                self._apply_action(Action(ActionType.DRAW, seat=seat))
        elif b.value == "discard":
            if self.selected_tile is not None:
                self._try_discard(self.selected_tile)
        elif b.value == "win":
            self._try_declare_win()
        elif b.value == "pass":
            if gs.phase == Phase.WAITING_CALLS and seat in gs.pending_calls:
                self._apply_action(Action(ActionType.PASS, seat=seat))
        elif b.value.startswith("call:"):
            idx = int(b.value.split(":")[1])
            calls = gs.pending_calls.get(seat, [])
            if 0 <= idx < len(calls):
                c = calls[idx]
                self._apply_action(Action(
                    ActionType.CALL, seat=seat,
                    meld_type=c.type, tiles_from_hand=list(c.tiles_from_hand),
                ))
        elif b.value == "kong":
            kongs = find_concealed_kongs(gs.players[seat].hand.concealed)
            if kongs:
                self._apply_action(Action(
                    ActionType.KONG_CONCEALED, seat=seat, tile=kongs[0],
                ))
        elif b.value == "play_again":
            self._reset_game()
        elif b.value == "quit":
            pygame.quit()
            sys.exit(0)

    def _try_discard(self, tile: Tile) -> None:
        gs = self.gs
        if gs.phase == Phase.WAITING_DISCARD and gs.current_seat == self.my_seat:
            self._apply_action(Action(ActionType.DISCARD, seat=self.my_seat, tile=tile))
            self.selected_tile = None

    def _try_declare_win(self) -> None:
        gs = self.gs
        p = gs.players[self.my_seat]
        if gs.phase == Phase.WAITING_DISCARD and gs.current_seat == self.my_seat:
            wt = p.hand.last_draw
            if wt and check_win(
                [t for t in p.hand.concealed if t != wt] + ([] if wt not in p.hand.concealed else []),
                p.hand.melds, wt, gs.gold,
            ).is_win:
                self._apply_action(Action(ActionType.DECLARE_WIN, seat=self.my_seat, tile=wt))
        elif gs.phase == Phase.WAITING_CALLS and gs.last_discard is not None:
            if check_win(p.hand.concealed, p.hand.melds,
                         gs.last_discard, gs.gold).is_win:
                self._apply_action(Action(
                    ActionType.DECLARE_WIN, seat=self.my_seat, tile=gs.last_discard,
                ))

    def _reset_game(self) -> None:
        """Start a fresh game with the same player names."""
        names = [p.name for p in self.gs.players]
        self.gs = GameState.new_game(names)
        self.selected_tile = None
        self.status_msg = ""

    def _apply_action(self, action: Action) -> None:
        if self.network is not None:
            self.network.send_action(action)
        else:
            try:
                self.gs.apply(action)
            except ValueError as e:
                self.status_msg = f"Illegal: {e}"

    # ------------------------------------------------ layout

    def _layout_my_hand(self) -> List[Tuple[Tile, pygame.Rect]]:
        p = self.gs.players[self.my_seat]
        tiles = sorted(p.hand.concealed)
        tw = self.tiles.tile_w
        th = self.tiles.tile_h
        total_w = len(tiles) * (tw + 4) - 4
        x0 = (self.w - total_w) // 2
        y = self.h - th - 40
        rects = []
        # Lift the just-drawn tile wherever it ends up in the sorted order
        # (only the first duplicate, so an already-present pair doesn't both
        # float).
        lifted = False
        on_my_turn = (
            self.gs.phase == Phase.WAITING_DISCARD
            and self.gs.current_seat == self.my_seat
            and p.hand.last_draw is not None
        )
        for i, t in enumerate(tiles):
            x = x0 + i * (tw + 4)
            dy = 0
            if on_my_turn and not lifted and t == p.hand.last_draw:
                dy = -12
                lifted = True
            rect = pygame.Rect(x, y + dy, tw, th)
            if self.selected_tile == t:
                rect.y -= 14
            rects.append((t, rect))
        return rects

    # ------------------------------------------------ drawing

    def _draw(self) -> None:
        self._update_layout()
        self._draw_felt()
        self._draw_top_bar()
        self._draw_center_info()
        self._draw_seats()
        self._draw_my_hand()
        self._draw_discards()
        self._draw_overlay_if_round_over()
        self._refresh_buttons()
        for b in self.buttons:
            b.draw(self.screen, self.font)
        self._draw_man_legend()
        self._draw_status()

    def _draw_felt(self) -> None:
        self.screen.fill(FELT_DARK)
        inner = pygame.Rect(30, 30, self.w - 60, self.h - 60)
        pygame.draw.rect(self.screen, FELT_GREEN, inner, border_radius=18)
        pygame.draw.rect(self.screen, IVORY_TEXT, inner, 2, border_radius=18)

    def _draw_top_bar(self) -> None:
        gs = self.gs
        bar = pygame.Rect(30, 30, self.w - 60, 44)
        pygame.draw.rect(self.screen, FELT_DARK, bar, border_radius=10)
        label = f"Round {gs.round_number}   Dealer: {gs.players[gs.dealer_seat].name}"
        if gs.deck and gs.deck.gold:
            label += f"   Gold tile: {gs.deck.gold}"
            label += f"   Wall: {gs.deck.remaining}"
        self.screen.blit(self.font_big.render(label, True, IVORY_TEXT), (50, 38))

    def _draw_center_info(self) -> None:
        gs = self.gs
        if gs.deck and gs.deck.gold:
            # Render the gold-tile indicator as small so it fits in the gap
            # between the top and bottom discard quadrants (which now flow
            # outward from the middle).
            gold_surf = self.tiles.small(gs.deck.gold)
            gx = self.w // 2 - gold_surf.get_width() // 2
            gy = self.h // 2 - gold_surf.get_height() // 2
            # Subtle plaque behind it so the tile reads on felt green.
            plaque = pygame.Rect(0, 0, gold_surf.get_width() + 16,
                                 gold_surf.get_height() + 22)
            plaque.center = (self.w // 2, self.h // 2)
            pygame.draw.rect(self.screen, FELT_DARK, plaque, border_radius=6)
            pygame.draw.rect(self.screen, GOLD, plaque, 1, border_radius=6)
            self.screen.blit(gold_surf, (gx, gy + 4))
            lbl = self.font_small.render("GOLD", True, GOLD)
            self.screen.blit(lbl, lbl.get_rect(midtop=(self.w // 2, plaque.top + 2)))

    def _draw_seats(self) -> None:
        """Draw the three other players' face-down hands around the table."""
        gs = self.gs
        back = self.tiles.opp_back()
        bw = back.get_width()
        bh = back.get_height()
        for seat in range(4):
            if seat == self.my_seat:
                continue
            rel = (seat - self.my_seat) % 4   # 1 = right, 2 = across, 3 = left
            p = gs.players[seat]
            n_tiles = len(p.hand.concealed)
            if rel == 2:  # opposite player (top)
                total_w = n_tiles * (bw + 3) - 3
                x0 = max(70, (self.w - total_w) // 2)
                y = 88
                for i in range(n_tiles):
                    self.screen.blit(back, (x0 + i * (bw + 3), y))
                self._draw_name_plate(seat, self.w // 2, 72, p)
            elif rel == 1 or rel == 3:
                rotated = _rotate(back, 90 if rel == 3 else -90)
                # After rotation: width is the source tile *height*, height is
                # the source tile *width*.
                r_w = rotated.get_width()
                r_h = rotated.get_height()
                total_h = n_tiles * (r_h + 3) - 3
                y0 = max(100, (self.h - total_h) // 2)
                if rel == 1:
                    x = self.w - r_w - 48
                    name_x = self.w - 80
                else:
                    x = 48
                    name_x = 80
                for i in range(n_tiles):
                    self.screen.blit(rotated, (x, y0 + i * (r_h + 3)))
                self._draw_name_plate(seat, name_x, y0 - 22, p)
            # melds (anchored relative to each seat's hand column)
            self._draw_exposed_melds(seat, rel)

    def _draw_name_plate(self, seat: int, x: int, y: int, p) -> None:
        dealer = (seat == self.gs.dealer_seat)
        label = f"{p.name}   ({p.score:+d})"
        if dealer:
            label = "● " + label
        txt = self.font.render(label, True, GOLD if dealer else IVORY_TEXT)
        self.screen.blit(txt, txt.get_rect(center=(x, y)))
        # flower count badge
        if p.hand.flowers:
            badge = self.font_small.render(
                f"flowers: {len(p.hand.flowers)}", True, IVORY_TEXT)
            self.screen.blit(badge, badge.get_rect(center=(x, y + 18)))

    def _draw_exposed_melds(self, seat: int, rel: int) -> None:
        """Render opponent melds as a horizontal strip of small tiles, placed
        immediately adjacent to that player's face-down hand.  Melds are
        separated by a small gap so pungs/chows stay visually distinct."""
        p = self.gs.players[seat]
        if not p.hand.melds:
            return
        sw = self.tiles.small_w
        sh = self.tiles.small_h
        gap = 2
        meld_gap = 8
        total_w = sum(len(m.tiles) * (sw + gap) - gap for m in p.hand.melds)
        total_w += meld_gap * (len(p.hand.melds) - 1)

        if rel == 2:  # top — right under their row of face-down tiles
            x = max(70, (self.w - total_w) // 2)
            y = 88 + self.tiles.opp_h + 6
        elif rel == 1:  # right — inset to the left of their column
            x = self.w - 48 - self.tiles.opp_h - 10 - total_w
            x = max(self.w // 2 + 40, x)
            y = self.h // 2 + 110
        else:  # rel == 3, left
            x = 48 + self.tiles.opp_h + 10
            x = min(self.w // 2 - 40 - total_w, x) if total_w else x
            y = self.h // 2 + 110

        for m_idx, m in enumerate(p.hand.melds):
            for t in m.tiles:
                surf = self.tiles.small(t)
                self.screen.blit(surf, (x, y))
                x += sw + gap
            x += meld_gap - gap

    def _draw_my_hand(self) -> None:
        p = self.gs.players[self.my_seat]
        sw = self.tiles.small_w
        sh = self.tiles.small_h
        # Flower rack
        if p.hand.flowers:
            x = 60; y = self.h - self.tiles.tile_h - sh - 96
            for t in p.hand.flowers:
                surf = self.tiles.small(t)
                self.screen.blit(surf, (x, y))
                x += surf.get_width() + 2
        # Exposed melds shown just above the hand
        if p.hand.melds:
            x = 60; y = self.h - self.tiles.tile_h - sh - 32
            for m in p.hand.melds:
                for t in m.tiles:
                    surf = self.tiles.small(t)
                    self.screen.blit(surf, (x, y))
                    x += surf.get_width() + 2
                x += 10
        # Concealed hand
        # Only highlight the freshly-drawn tile while it's still *my* turn to
        # discard — once I've played it, there's no "last draw" to spotlight.
        highlight_last_draw = (
            self.gs.phase == Phase.WAITING_DISCARD
            and self.gs.current_seat == self.my_seat
            and p.hand.last_draw is not None
        )
        for tile, rect in self._layout_my_hand():
            self.screen.blit(self.tiles.face(tile), rect)
            # highlight the gold (permanent round-long reminder)
            if self.gs.deck and tile == self.gs.deck.gold:
                pygame.draw.rect(self.screen, GOLD, rect, 3, border_radius=8)
            # highlight the tile I just drew this turn
            if highlight_last_draw and tile == p.hand.last_draw:
                self._highlight_tile(rect, (120, 220, 255))
                highlight_last_draw = False   # only the first occurrence

    def _draw_discards(self) -> None:
        """Show each seat's discards as a tidy grid in the centre of the
        table.  The most recently discarded tile (still ``gs.last_discard``,
        unless it's been called by someone) is outlined in gold so it's easy
        to spot at a glance."""
        gs = self.gs
        sw = self.tiles.small_w
        sh = self.tiles.small_h
        gap = 3
        cx, cy = self.w // 2, self.h // 2

        # How far each quadrant sits from the table centre.  Big enough to
        # keep tiles clear of the gold-tile indicator (a small tile + label
        # sitting dead-centre) and the surrounding name plates.
        pad_x = max(70, sw + 30)
        pad_y = max(56, sh + 22)

        # Bounded rows/cols per quadrant.  Recomputed from viewport so the
        # pool shrinks sensibly in smaller windows.
        avail_top_bot_w = max(220, self.w // 2)
        avail_side_h = max(160, self.h // 2 - 120)
        per_row = max(6, min(10, (avail_top_bot_w) // (sw + gap)))
        per_col = max(4, min(7, (avail_side_h) // (sh + gap)))

        for seat in range(4):
            rel = (seat - self.my_seat) % 4
            tiles = gs.discards[seat]
            if not tiles:
                continue
            last_i = len(tiles) - 1
            last_is_live = (
                gs.last_discarder == seat
                and gs.last_discard is not None
                and tiles[-1] == gs.last_discard
            )
            for i, t in enumerate(tiles):
                if rel == 0:        # bottom (me)
                    row = i // per_row
                    col = i % per_row
                    x = cx - (per_row * (sw + gap)) // 2 + col * (sw + gap)
                    y = cy + pad_y + row * (sh + gap)
                elif rel == 2:      # across (top)
                    row = i // per_row
                    col = i % per_row
                    x = cx - (per_row * (sw + gap)) // 2 + col * (sw + gap)
                    y = cy - pad_y - sh - row * (sh + gap)
                elif rel == 1:      # right
                    row = i // per_col
                    col = i % per_col
                    x = cx + pad_x + row * (sw + gap)
                    y = cy - (per_col * (sh + gap)) // 2 + col * (sh + gap)
                else:               # left (rel == 3)
                    row = i // per_col
                    col = i % per_col
                    x = cx - pad_x - sw - row * (sw + gap)
                    y = cy - (per_col * (sh + gap)) // 2 + col * (sh + gap)
                surf = self.tiles.small(t)
                rect = surf.get_rect(topleft=(x, y))
                self.screen.blit(surf, rect)
                if last_is_live and i == last_i:
                    self._highlight_tile(rect, GOLD)

    # ------------------------------------------------ highlight helper

    def _highlight_tile(self, rect: pygame.Rect, color: Tuple[int, int, int]) -> None:
        """Outline a tile to draw the eye to it — used for the most recently
        discarded / drawn tile.  Drawn as a pulsing soft halo + solid border
        so it's obvious even on a busy felt."""
        ticks = pygame.time.get_ticks()
        # 0..1 sinewave at ~1.2Hz for a gentle pulse.
        pulse = 0.5 + 0.5 * math.sin(ticks / 160.0)
        halo = rect.inflate(10, 10)
        # Soft halo via per-pixel alpha surface so the glow actually reads on
        # felt green without looking like a harsh box.
        halo_surf = pygame.Surface(halo.size, pygame.SRCALPHA)
        alpha = int(60 + 80 * pulse)
        pygame.draw.rect(
            halo_surf, (*color, alpha), halo_surf.get_rect(),
            border_radius=8,
        )
        self.screen.blit(halo_surf, halo.topleft)
        pygame.draw.rect(self.screen, color, rect.inflate(4, 4), 3, border_radius=5)

    # ------------------------------------------------ buttons panel

    def _refresh_buttons(self) -> None:
        gs = self.gs
        seat = self.my_seat
        self.buttons = []
        y = self.h - 50
        x = self.w - 20

        def add(label: str, value: str) -> None:
            nonlocal x
            b = Button(pygame.Rect(x - 110, y, 100, 34), label, value)
            self.buttons.append(b)
            x -= 115

        phase = gs.phase
        if phase == Phase.WAITING_DRAW and gs.current_seat == seat:
            add("Draw", "draw")
        elif phase == Phase.WAITING_DISCARD and gs.current_seat == seat:
            if self.selected_tile is not None:
                add("Discard", "discard")
            p = gs.players[seat]
            if p.hand.last_draw is not None:
                temp = [t for t in p.hand.concealed if t != p.hand.last_draw]
                if check_win(temp, p.hand.melds, p.hand.last_draw, gs.gold).is_win:
                    add("Mahjong!", "win")
            if find_concealed_kongs(p.hand.concealed):
                add("Kong", "kong")
        elif phase == Phase.WAITING_CALLS and seat in gs.pending_calls:
            add("Pass", "pass")
            for i, c in enumerate(gs.pending_calls[seat]):
                lbl = {
                    MeldType.CHOW: "Chow",
                    MeldType.PUNG: "Pung",
                    MeldType.KONG_EXPOSED: "Kong",
                }.get(c.type, c.type.value)
                add(lbl, f"call:{i}")
            if check_win(
                gs.players[seat].hand.concealed, gs.players[seat].hand.melds,
                gs.last_discard, gs.gold,
            ).is_win:
                add("Mahjong!", "win")
        elif phase == Phase.ROUND_OVER:
            bw, bh = 140, 40
            gap = 20
            total_w = bw * 2 + gap
            x0 = (self.w - total_w) // 2
            by = self.h // 2 + 200
            self.buttons.append(Button(pygame.Rect(x0, by, bw, bh), "Play Again", "play_again"))
            self.buttons.append(Button(pygame.Rect(x0 + bw + gap, by, bw, bh), "Quit", "quit"))

    # ------------------------------------------------ man-tile legend

    def _draw_man_legend(self) -> None:
        """Small panel in the bottom-right corner explaining Man tile characters."""
        if not self.show_legend:
            return

        row_h    = 20
        padding  = 8
        char_col = 22   # width reserved for the CJK glyph column
        panel_w  = 200
        title_h  = 22
        panel_h  = title_h + len(MAN_LEGEND) * row_h + padding * 2
        hint_h   = 16

        # Anchor to bottom-right of the felt area (inside the border).
        px = self.w - panel_w - 40
        py = self.h - panel_h - hint_h - 50

        # Semi-transparent background
        panel_surf = pygame.Surface((panel_w, panel_h + hint_h), pygame.SRCALPHA)
        panel_surf.fill((8, 32, 18, 210))
        pygame.draw.rect(panel_surf, IVORY_TEXT,
                         panel_surf.get_rect(), 1, border_radius=6)
        self.screen.blit(panel_surf, (px, py))

        # Title row
        title = self.font.render("Man Tiles  (Characters)", True, GOLD)
        self.screen.blit(title, (px + padding, py + padding))

        y = py + padding + title_h
        for cjk_char, english in MAN_LEGEND:
            # CJK character (red for numerals, ivory for 萬)
            if self.font_cjk is not None:
                color = RED if cjk_char != "萬" else IVORY_TEXT
                char_surf = self.font_cjk.render(cjk_char, True, color)
                self.screen.blit(char_surf, (px + padding, y))
            # English label
            eng_surf = self.font_small.render(english, True, IVORY_TEXT)
            self.screen.blit(eng_surf, (px + padding + char_col, y + 3))
            y += row_h

        # Dismiss hint
        hint = self.font_small.render("  [L] show/hide", True, (120, 140, 120))
        self.screen.blit(hint, (px + padding, py + panel_h + 1))

    # ------------------------------------------------ status + overlay

    def _draw_status(self) -> None:
        if not self.status_msg:
            return
        surf = self.font.render(self.status_msg, True, RED)
        self.screen.blit(surf, (40, self.h - 30))

    def _draw_overlay_if_round_over(self) -> None:
        gs = self.gs
        if gs.phase != Phase.ROUND_OVER:
            return
        overlay = pygame.Surface((self.w, self.h), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 160))
        self.screen.blit(overlay, (0, 0))
        if gs.winning_player is None:
            title = "Draw game — no winner"
        else:
            title = f"{gs.players[gs.winning_player].name} wins!"
        t = self.font_big.render(title, True, GOLD)
        self.screen.blit(t, t.get_rect(center=(self.w // 2, 220)))
        if gs.winning_breakdown:
            from ..game.score import format_breakdown
            lines = format_breakdown(gs.winning_breakdown).split("\n")
            y = 270
            for ln in lines:
                s = self.font.render(ln, True, IVORY_TEXT)
                self.screen.blit(s, s.get_rect(center=(self.w // 2, y)))
                y += 26


# ------------------------------------------------------------- entry point


def main(argv: Optional[List[str]] = None) -> None:
    parser = argparse.ArgumentParser(prog="fuzhou_mahjong")
    parser.add_argument("--seed", type=int, default=None,
                        help="deterministic deck seed")
    parser.add_argument("--solo", action="store_true",
                        help="play against 3 AI bots locally")
    parser.add_argument("--host", type=str,
                        help="remote server host:port for online play")
    parser.add_argument("--room", type=str, default="",
                        help="room code to join")
    parser.add_argument("--name", type=str, default="You",
                        help="your display name")
    args = parser.parse_args(argv)

    if args.host:
        from ..net.client import NetworkClient    # imported lazily
        nc = NetworkClient(args.host, args.room, args.name)
        nc.run_with_pygame()
        return

    # Local solo vs 3 AIs.
    gs = GameState.new_game([args.name, "AI-East", "AI-North", "AI-West"],
                             seed=args.seed)
    client = Client(
        my_seat=0,
        local_ais=[1, 2, 3],
        gs=gs,
    )
    client.run()


if __name__ == "__main__":
    main()
EXT,
                         panel_surf.get_rect(), 1, border_radius=6)
        self.screen.blit(panel_surf, (px, py))

        # Title row
        title = self.font.render("Man Tiles  (Characters)", True, GOLD)
        self.screen.blit(title, (px + padding, py + padding))

        y = py + padding + title_h
        for cjk_char, english in MAN_LEGEND:
            # CJK character (red for numerals, ivory for Wan)
            if self.font_cjk is not None:
                color = RED if cjk_char != "\u842c" else IVORY_TEXT
                char_surf = self.font_cjk.render(cjk_char, True, color)
                self.screen.blit(char_surf, (px + padding, y))
            # English label
            eng_surf = self.font_small.render(english, True, IVORY_TEXT)
            self.screen.blit(eng_surf, (px + padding + char_col, y + 3))
            y += row_h

        # Dismiss hint
        hint = self.font_small.render("  [L] show/hide", True, (120, 140, 120))
        self.screen.blit(hint, (px + padding, py + panel_h + 1))

    # ------------------------------------------------ status + overlay

    def _draw_status(self) -> None:
        if not self.status_msg:
            return
        surf = self.font.render(self.status_msg, True, RED)
        self.screen.blit(surf, (40, self.h - 30))

    def _draw_overlay_if_round_over(self) -> None:
        gs = self.gs
        if gs.phase != Phase.ROUND_OVER:
            return
        overlay = pygame.Surface((self.w, self.h), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 160))
        self.screen.blit(overlay, (0, 0))
        if gs.winning_player is None:
            title = "Draw game -- no winner"
        else:
            title = f"{gs.players[gs.winning_player].name} wins!"
        t = self.font_big.render(title, True, GOLD)
        self.screen.blit(t, t.get_rect(center=(self.w // 2, 220)))
        if gs.winning_breakdown:
            from ..game.score import format_breakdown
            lines = format_breakdown(gs.winning_breakdown).split("\n")
            y = 270
            for ln in lines:
                s = self.font.render(ln, True, IVORY_TEXT)
                self.screen.blit(s, s.get_rect(center=(self.w // 2, y)))
                y += 26


# ------------------------------------------------------------- entry point


def main(argv=None):
    parser = argparse.ArgumentParser(prog="fuzhou_mahjong")
    parser.add_argument("--seed", type=int, default=None,
                        help="deterministic deck seed")
    parser.add_argument("--solo", action="store_true",
                        help="play against 3 AI bots locally")
    parser.add_argument("--host", type=str,
                        help="remote server host:port for online play")
    parser.add_argument("--room", type=str, default="",
                        help="room code to join")
    parser.add_argument("--name", type=str, default="You",
                        help="your display name")
    args = parser.parse_args(argv)

    if args.host:
        from ..net.client import NetworkClient
        nc = NetworkClient(args.host, args.room, args.name)
        nc.run_with_pygame()
        return

    gs = GameState.new_game([args.name, "AI-East", "AI-North", "AI-West"],
                             seed=args.seed)
    client = Client(
        my_seat=0,
        local_ais=[1, 2, 3],
        gs=gs,
    )
    client.run()


if __name__ == "__main__":
    main()
        gs=gs,
    )
    client.run()


if __name__ == "__main__":
    main()
