"""
Pygame client for Fuzhou Mahjong.

Architecture
------------
The client holds a `GameState` that is either (a) owned locally when playing
against AI, or (b) a mirror kept in sync with a remote server when playing
online.  Rendering is a pure function of the current state; input events are
translated into `Action`s that are either applied locally or forwarded to the
server.

Authentic table styling
-----------------------
  * Deep green felt background with a subtle vignette.
  * Ivory tiles generated by ``render_tiles.py``.
  * Four seats laid out around the table (South is the local player),
    with other seats rendering as face-down backs unless the game is in a
    "show hands" mode.
  * Discards pile up in the centre rectangle.
  * Score bar along the top shows each player's running score and who the
    dealer is.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pygame

from ..game import (
    Action, ActionType, GameState, MeldType, Phase, Tile, check_win,
    find_calls, find_concealed_kongs,
)
from ..game.ai import AIPlayer
from . import render_tiles


# ------------------------------------------------------------- constants

WINDOW_W, WINDOW_H = 1280, 800
FELT_GREEN = (20, 90, 55)
FELT_DARK = (14, 60, 38)
IVORY_TEXT = (248, 238, 212)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GOLD = (218, 170, 50)
RED = (200, 40, 40)
BTN = (80, 60, 40)
BTN_HOVER = (120, 90, 60)

FPS = 60


def _get_asset_dir() -> Path:
    """Return the tiles asset directory, works both normally and inside a
    PyInstaller bundle (where sys._MEIPASS holds the extracted package root)."""
    if getattr(sys, "frozen", False):
        # Running as a PyInstaller .exe — assets are extracted to _MEIPASS
        base = Path(sys._MEIPASS)  # type: ignore[attr-defined]
    else:
        base = Path(__file__).resolve().parent.parent
    return base / "assets" / "tiles"


ASSET_DIR = _get_asset_dir()


# ------------------------------------------------------------- asset loader


class TileCache:
    """Loads + caches the per-tile PNGs.  Auto-generates them if missing."""

    def __init__(self, scale: float = 0.8):
        if not (ASSET_DIR / "back.png").exists():
            render_tiles.generate_all(ASSET_DIR)
        self._images: Dict[str, pygame.Surface] = {}
        self._small: Dict[str, pygame.Surface] = {}
        self.scale = scale
        for f in ASSET_DIR.glob("*.png"):
            img = pygame.image.load(str(f)).convert_alpha()
            img = pygame.transform.smoothscale(
                img,
                (int(img.get_width() * scale), int(img.get_height() * scale)),
            )
            self._images[f.stem] = img
            small = pygame.transform.smoothscale(
                img,
                (int(img.get_width() * 0.6), int(img.get_height() * 0.6)),
            )
            self._small[f.stem] = small

    def _key(self, tile: Tile) -> str:
        return tile.to_id().replace(":", "_")

    def face(self, tile: Tile) -> pygame.Surface:
        return self._images[self._key(tile)]

    def small(self, tile: Tile) -> pygame.Surface:
        return self._small[self._key(tile)]

    def back(self) -> pygame.Surface:
        return self._images["back"]

    @property
    def tile_w(self) -> int:
        return self.back().get_width()

    @property
    def tile_h(self) -> int:
        return self.back().get_height()


# ------------------------------------------------------------- layout helpers


def _rotate(surf: pygame.Surface, deg: int) -> pygame.Surface:
    return pygame.transform.rotate(surf, deg) if deg else surf


# ------------------------------------------------------------- button


class Button:
    def __init__(self, rect: pygame.Rect, label: str, value: str = ""):
        self.rect = rect
        self.label = label
        self.value = value or label
        self.hovered = False
        self.enabled = True

    def draw(self, surf: pygame.Surface, font: pygame.font.Font) -> None:
        color = BTN_HOVER if self.hovered and self.enabled else BTN
        if not self.enabled:
            color = (60, 50, 40)
        pygame.draw.rect(surf, color, self.rect, border_radius=6)
        pygame.draw.rect(surf, IVORY_TEXT, self.rect, 2, border_radius=6)
        txt = font.render(self.label, True, IVORY_TEXT if self.enabled else (140, 130, 110))
        surf.blit(txt, txt.get_rect(center=self.rect.center))

    def handle(self, event) -> bool:
        if not self.enabled:
            return False
        if event.type == pygame.MOUSEMOTION:
            self.hovered = self.rect.collidepoint(event.pos)
        elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            if self.rect.collidepoint(event.pos):
                return True
        return False


# ------------------------------------------------------------- main client


class Client:
    """Runs the Pygame loop against either a local AI game or a remote session."""

    def __init__(
        self,
        my_seat: int = 0,
        local_ais: Optional[List[int]] = None,
        gs: Optional[GameState] = None,
        network: Optional["NetworkClient"] = None,
        seed: Optional[int] = None,
    ):
        pygame.init()
        pygame.display.set_caption("Fuzhou Mahjong")
        self.screen = pygame.display.set_mode((WINDOW_W, WINDOW_H))
        self.clock = pygame.time.Clock()
        self.tiles = TileCache(scale=0.75)
        self.my_seat = my_seat
        self.network = network
        self.font = pygame.font.SysFont("arial", 18)
        self.font_big = pygame.font.SysFont("arial", 28, bold=True)
        self.font_small = pygame.font.SysFont("arial", 14)

        self.gs = gs or GameState.new_game(
            ["You", "Player 2", "Player 3", "Player 4"], seed=seed,
        )
        self.local_ais: Dict[int, AIPlayer] = {}
        for seat in (local_ais or []):
            self.local_ais[seat] = AIPlayer(seat, seed=seat)

        self.selected_tile: Optional[Tile] = None
        self.status_msg = ""
        self.buttons: List[Button] = []

    # ------------------------------------------------ running

    def run(self) -> None:
        try:
            while True:
                self._tick()
        except SystemExit:
            pygame.quit()

    def _tick(self) -> None:
        self._run_ais()
        self._handle_events()
        self._draw()
        pygame.display.flip()
        self.clock.tick(FPS)

    # ------------------------------------------------ AI driver

    def _run_ais(self) -> None:
        if self.network is not None:
            return   # the server drives turns for remote bots
        gs = self.gs
        if gs.phase == Phase.WAITING_DRAW and gs.current_seat in self.local_ais:
            gs.apply(Action(ActionType.DRAW, seat=gs.current_seat))
        elif gs.phase == Phase.WAITING_DISCARD and gs.current_seat in self.local_ais:
            ai = self.local_ais[gs.current_seat]
            pygame.time.delay(400)   # slight pacing so it's readable
            gs.apply(ai.act_on_turn(gs))
        elif gs.phase == Phase.WAITING_CALLS:
            for seat, calls in list(gs.pending_calls.items()):
                if seat in self.local_ais:
                    gs.apply(self.local_ais[seat].act_on_call(gs, calls))
                    if gs.phase != Phase.WAITING_CALLS:
                        break

    # ------------------------------------------------ input

    def _handle_events(self) -> None:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit(0)
            if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                pygame.quit(); sys.exit(0)

            for b in self.buttons:
                if b.handle(event):
                    self._on_button(b)

            if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                self._on_click(event.pos)

    def _on_click(self, pos: Tuple[int, int]) -> None:
        # Click on own concealed tiles to select / discard.
        hand_rects = self._layout_my_hand()
        for tile, rect in hand_rects:
            if rect.collidepoint(pos):
                if self.selected_tile == tile:
                    self._try_discard(tile)
                else:
                    self.selected_tile = tile
                return

    def _on_button(self, b: Button) -> None:
        gs = self.gs
        seat = self.my_seat
        if b.value == "draw":
            if gs.phase == Phase.WAITING_DRAW and gs.current_seat == seat:
                self._apply_action(Action(ActionType.DRAW, seat=seat))
        elif b.value == "discard":
            if self.selected_tile is not None:
                self._try_discard(self.selected_tile)
        elif b.value == "win":
            self._try_declare_win()
        elif b.value == "pass":
            if gs.phase == Phase.WAITING_CALLS and seat in gs.pending_calls:
                self._apply_action(Action(ActionType.PASS, seat=seat))
        elif b.value.startswith("call:"):
            idx = int(b.value.split(":")[1])
            calls = gs.pending_calls.get(seat, [])
            if 0 <= idx < len(calls):
                c = calls[idx]
                self._apply_action(Action(
                    ActionType.CALL, seat=seat,
                    meld_type=c.type, tiles_from_hand=list(c.tiles_from_hand),
                ))
        elif b.value == "kong":
            kongs = find_concealed_kongs(gs.players[seat].hand.concealed)
            if kongs:
                self._apply_action(Action(
                    ActionType.KONG_CONCEALED, seat=seat, tile=kongs[0],
                ))

    def _try_discard(self, tile: Tile) -> None:
        gs = self.gs
        if gs.phase == Phase.WAITING_DISCARD and gs.current_seat == self.my_seat:
            self._apply_action(Action(ActionType.DISCARD, seat=self.my_seat, tile=tile))
            self.selected_tile = None

    def _try_declare_win(self) -> None:
        gs = self.gs
        p = gs.players[self.my_seat]
        if gs.phase == Phase.WAITING_DISCARD and gs.current_seat == self.my_seat:
            wt = p.hand.last_draw
            if wt and check_win(
                [t for t in p.hand.concealed if t != wt] + ([] if wt not in p.hand.concealed else []),
                p.hand.melds, wt, gs.gold,
            ).is_win:
                self._apply_action(Action(ActionType.DECLARE_WIN, seat=self.my_seat, tile=wt))
        elif gs.phase == Phase.WAITING_CALLS and gs.last_discard is not None:
            if check_win(p.hand.concealed, p.hand.melds,
                         gs.last_discard, gs.gold).is_win:
                self._apply_action(Action(
                    ActionType.DECLARE_WIN, seat=self.my_seat, tile=gs.last_discard,
                ))

    def _apply_action(self, action: Action) -> None:
        if self.network is not None:
            self.network.send_action(action)
        else:
            try:
                self.gs.apply(action)
            except ValueError as e:
                self.status_msg = f"Illegal: {e}"

    # ------------------------------------------------ layout

    def _layout_my_hand(self) -> List[Tuple[Tile, pygame.Rect]]:
        p = self.gs.players[self.my_seat]
        tiles = sorted(p.hand.concealed)
        tw = self.tiles.tile_w
        th = self.tiles.tile_h
        total_w = len(tiles) * (tw + 4) - 4
        x0 = (WINDOW_W - total_w) // 2
        y = WINDOW_H - th - 40
        rects = []
        for i, t in enumerate(tiles):
            x = x0 + i * (tw + 4)
            # Lift last draw a bit
            dy = -12 if (t == p.hand.last_draw and i == len(tiles) - 1) else 0
            rect = pygame.Rect(x, y + dy, tw, th)
            if self.selected_tile == t:
                rect.y -= 14
            rects.append((t, rect))
        return rects

    # ------------------------------------------------ drawing

    def _draw(self) -> None:
        self._draw_felt()
        self._draw_top_bar()
        self._draw_center_info()
        self._draw_seats()
        self._draw_my_hand()
        self._draw_discards()
        self._refresh_buttons()
        for b in self.buttons:
            b.draw(self.screen, self.font)
        self._draw_status()
        self._draw_overlay_if_round_over()

    def _draw_felt(self) -> None:
        self.screen.fill(FELT_DARK)
        inner = pygame.Rect(30, 30, WINDOW_W - 60, WINDOW_H - 60)
        pygame.draw.rect(self.screen, FELT_GREEN, inner, border_radius=18)
        pygame.draw.rect(self.screen, IVORY_TEXT, inner, 2, border_radius=18)

    def _draw_top_bar(self) -> None:
        gs = self.gs
        bar = pygame.Rect(30, 30, WINDOW_W - 60, 44)
        pygame.draw.rect(self.screen, FELT_DARK, bar, border_radius=10)
        label = f"Round {gs.round_number}   Dealer: {gs.players[gs.dealer_seat].name}"
        if gs.deck and gs.deck.gold:
            label += f"   Gold tile: {gs.deck.gold}"
            label += f"   Wall: {gs.deck.remaining}"
        self.screen.blit(self.font_big.render(label, True, IVORY_TEXT), (50, 38))

    def _draw_center_info(self) -> None:
        gs = self.gs
        if gs.deck and gs.deck.gold:
            gold_surf = self.tiles.face(gs.deck.gold)
            cx = WINDOW_W // 2 - gold_surf.get_width() // 2
            cy = WINDOW_H // 2 - gold_surf.get_height() - 20
            self.screen.blit(gold_surf, (cx, cy))
            lbl = self.font_small.render("GOLD", True, GOLD)
            self.screen.blit(lbl, (cx + gold_surf.get_width() // 2 - lbl.get_width() // 2,
                                   cy - 18))

    def _draw_seats(self) -> None:
        """Draw the three other players' face-down hands around the table."""
        gs = self.gs
        for seat in range(4):
            if seat == self.my_seat:
                continue
            rel = (seat - self.my_seat) % 4   # 1 = right, 2 = across, 3 = left
            p = gs.players[seat]
            back = self.tiles.back()
            n_tiles = len(p.hand.concealed)
            if rel == 2:  # opposite player (top)
                total_w = n_tiles * (back.get_width() + 3)
                x0 = (WINDOW_W - total_w) // 2
                y = 90
                for i in range(n_tiles):
                    self.screen.blit(back, (x0 + i * (back.get_width() + 3), y))
                self._draw_name_plate(seat, WINDOW_W // 2, 75, p)
            elif rel == 1 or rel == 3:
                rotated = _rotate(back, 90 if rel == 3 else -90)
                total_h = n_tiles * (rotated.get_height() + 3)
                y0 = (WINDOW_H - total_h) // 2
                if rel == 1:
                    x = WINDOW_W - rotated.get_width() - 50
                    name_x = WINDOW_W - 90
                else:
                    x = 50
                    name_x = 90
                for i in range(n_tiles):
                    self.screen.blit(rotated, (x, y0 + i * (rotated.get_height() + 3)))
                self._draw_name_plate(seat, name_x, y0 - 22, p)
            # melds
            self._draw_exposed_melds(seat, rel)

    def _draw_name_plate(self, seat: int, x: int, y: int, p) -> None:
        dealer = (seat == self.gs.dealer_seat)
        label = f"{p.name}   ({p.score:+d})"
        if dealer:
            label = "● " + label
        txt = self.font.render(label, True, GOLD if dealer else IVORY_TEXT)
        self.screen.blit(txt, txt.get_rect(center=(x, y)))
        # flower count badge
        if p.hand.flowers:
            badge = self.font_small.render(
                f"flowers: {len(p.hand.flowers)}", True, IVORY_TEXT)
            self.screen.blit(badge, badge.get_rect(center=(x, y + 18)))

    def _draw_exposed_melds(self, seat: int, rel: int) -> None:
        p = self.gs.players[seat]
        if not p.hand.melds:
            return
        x = 100 if rel != 1 else WINDOW_W - 220
        y = 130 + 30 * seat
        small = self.tiles.small(p.hand.melds[0].tiles[0]) if p.hand.melds else None
        if small is None:
            return
        base_x = x
        for m in p.hand.melds:
            for t in m.tiles:
                surf = self.tiles.small(t)
                self.screen.blit(surf, (base_x, y))
                base_x += surf.get_width() + 2
            base_x += 8

    def _draw_my_hand(self) -> None:
        p = self.gs.players[self.my_seat]
        # Flower rack
        if p.hand.flowers:
            x = 60; y = WINDOW_H - self.tiles.tile_h - 160
            for t in p.hand.flowers:
                surf = self.tiles.small(t)
                self.screen.blit(surf, (x, y))
                x += surf.get_width() + 2
        # Exposed melds shown just above the hand
        if p.hand.melds:
            x = 60; y = WINDOW_H - self.tiles.tile_h - 110
            for m in p.hand.melds:
                for t in m.tiles:
                    surf = self.tiles.small(t)
                    self.screen.blit(surf, (x, y))
                    x += surf.get_width() + 2
                x += 10
        # Concealed hand
        for tile, rect in self._layout_my_hand():
            self.screen.blit(self.tiles.face(tile), rect)
            # highlight the gold
            if self.gs.deck and tile == self.gs.deck.gold:
                pygame.draw.rect(self.screen, GOLD, rect, 3, border_radius=8)

    def _draw_discards(self) -> None:
        """Show each seat's discards stacking outward from the centre."""
        tile_w = self.tiles.small(Tile.m(1)).get_width()
        tile_h = self.tiles.small(Tile.m(1)).get_height()
        cx, cy = WINDOW_W // 2, WINDOW_H // 2 + 30
        per_row = 12
        for seat in range(4):
            rel = (seat - self.my_seat) % 4
            tiles = self.gs.discards[seat]
            for i, t in enumerate(tiles):
                row = i // per_row
                col = i % per_row
                if rel == 0:   # me (bottom of centre area)
                    x = cx - (per_row * (tile_w + 2)) // 2 + col * (tile_w + 2)
                    y = cy + 20 + row * (tile_h + 2)
                elif rel == 2:  # across (top)
                    x = cx - (per_row * (tile_w + 2)) // 2 + col * (tile_w + 2)
                    y = cy - 20 - tile_h - row * (tile_h + 2)
                elif rel == 1:  # right
                    x = cx + 90 + row * (tile_w + 2)
                    y = cy - (per_row * (tile_h + 2)) // 2 + col * (tile_h + 2)
                else:           # left
                    x = cx - 90 - tile_w - row * (tile_w + 2)
                    y = cy - (per_row * (tile_h + 2)) // 2 + col * (tile_h + 2)
                self.screen.blit(self.tiles.small(t), (x, y))

    # ------------------------------------------------ buttons panel

    def _refresh_buttons(self) -> None:
        gs = self.gs
        seat = self.my_seat
        self.buttons = []
        y = WINDOW_H - 50
        x = WINDOW_W - 20

        def add(label: str, value: str) -> None:
            nonlocal x
            b = Button(pygame.Rect(x - 110, y, 100, 34), label, value)
            self.buttons.append(b)
            x -= 115

        phase = gs.phase
        if phase == Phase.WAITING_DRAW and gs.current_seat == seat:
            add("Draw", "draw")
        elif phase == Phase.WAITING_DISCARD and gs.current_seat == seat:
            if self.selected_tile is not None:
                add("Discard", "discard")
            p = gs.players[seat]
            if p.hand.last_draw is not None:
                temp = [t for t in p.hand.concealed if t != p.hand.last_draw]
                if check_win(temp, p.hand.melds, p.hand.last_draw, gs.gold).is_win:
                    add("Mahjong!", "win")
            if find_concealed_kongs(p.hand.concealed):
                add("Kong", "kong")
        elif phase == Phase.WAITING_CALLS and seat in gs.pending_calls:
            add("Pass", "pass")
            for i, c in enumerate(gs.pending_calls[seat]):
                lbl = {
                    MeldType.CHOW: "Chow",
                    MeldType.PUNG: "Pung",
                    MeldType.KONG_EXPOSED: "Kong",
                }.get(c.type, c.type.value)
                add(lbl, f"call:{i}")
            if check_win(
                gs.players[seat].hand.concealed, gs.players[seat].hand.melds,
                gs.last_discard, gs.gold,
            ).is_win:
                add("Mahjong!", "win")

    # ------------------------------------------------ status + overlay

    def _draw_status(self) -> None:
        if not self.status_msg:
            return
        surf = self.font.render(self.status_msg, True, RED)
        self.screen.blit(surf, (40, WINDOW_H - 30))

    def _draw_overlay_if_round_over(self) -> None:
        gs = self.gs
        if gs.phase != Phase.ROUND_OVER:
            return
        overlay = pygame.Surface((WINDOW_W, WINDOW_H), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 160))
        self.screen.blit(overlay, (0, 0))
        if gs.winning_player is None:
            title = "Draw game — no winner"
        else:
            title = f"{gs.players[gs.winning_player].name} wins!"
        t = self.font_big.render(title, True, GOLD)
        self.screen.blit(t, t.get_rect(center=(WINDOW_W // 2, 220)))
        if gs.winning_breakdown:
            from ..game.score import format_breakdown
            lines = format_breakdown(gs.winning_breakdown).split("\n")
            y = 270
            for ln in lines:
                s = self.font.render(ln, True, IVORY_TEXT)
                self.screen.blit(s, s.get_rect(center=(WINDOW_W // 2, y)))
                y += 26


# ------------------------------------------------------------- entry point


def main(argv: Optional[List[str]] = None) -> None:
    parser = argparse.ArgumentParser(prog="fuzhou_mahjong")
    parser.add_argument("--seed", type=int, default=None,
                        help="deterministic deck seed")
    parser.add_argument("--solo", action="store_true",
                        help="play against 3 AI bots locally")
    parser.add_argument("--host", type=str,
                        help="remote server host:port for online play")
    parser.add_argument("--room", type=str, default="",
                        help="room code to join")
    parser.add_argument("--name", type=str, default="You",
                        help="your display name")
    args = parser.parse_args(argv)

    if args.host:
        from ..net.client import NetworkClient    # imported lazily
        nc = NetworkClient(args.host, args.room, args.name)
        nc.run_with_pygame()
        return

    # Local solo vs 3 AIs.
    gs = GameState.new_game([args.name, "AI-East", "AI-North", "AI-West"],
                             seed=args.seed)
    client = Client(
        my_seat=0,
        local_ais=[1, 2, 3],
        gs=gs,
    )
    client.run()


if __name__ == "__main__":
    main()
